name: Script
# on: workflow_dispatch
on: 
    schedule:
    - cron: "**/10 * * * *"
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        
        - name: checkout repo content
          uses: actions/checkout@v2 # checkout the repository content to github runner.
        - name: PHP Runner
          uses: franzliedke/gh-action-php@0.2.0

        - name: execute php script # run the script.php
          run: |
              php script.php fbiego ${{ secrets.flx_token }}
              
        - name: commit files
          run: |
                git config --local user.email "mike.owino40@yahoo.com"
                git config --local user.name "MikeOwino"
                git add -A
                git commit -m "run script" -a
        
        - name: push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main 
